name: python-ml
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.3
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.4
  - cloudpickle=2.2.1
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - flatbuffers=2.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gast=0.4.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gts=0.7.6
  - h5py=3.9.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - importlib-metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libtool=2.4.6
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.2
  - openjpeg=2.3.0
  - openssl=1.1.1v
  - opt_einsum=3.3.0
  - packaging=23.0
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - plotly=5.9.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python-tzdata=2023.3
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tenacity=8.2.2
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-estimator=2.12.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.7.1
  - treelib=1.6.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.35.1
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - xlrd=2.0.1
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - array-record==0.4.1
      - brewer2mpl==1.4.1
      - charset-normalizer==3.2.0
      - chart-studio==1.1.0
      - dm-tree==0.1.8
      - etils==1.4.1
      - ggplot==0.11.5
      - googleapis-common-protos==1.60.0
      - importlib-resources==6.0.1
      - promise==2.3
      - pyclust==0.2.0
      - python-graphviz==0.20.1
      - retrying==1.3.4
      - tensorflow-datasets==4.9.2
      - tensorflow-metadata==1.14.0
      - toml==0.10.2
      - tqdm==4.66.1
